# Generated by Django 4.2.5 on 2023-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='photos')),
                ('des', models.TextField()),
            ],
        ),
    ]
