# Generated by Django 4.2.5 on 2023-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='flowers')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='high',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='images')),
                ('des', models.TextField()),
            ],
        ),
    ]
